### PR TITLE
wsgi is a reserved namespace on AWS lambda via zappa

### PR DESCRIPTION
**Pull request by palewire**
Can we call this file something else?

### CODE REVIEW

**Comment by iandees** [comment]
Yep, but can you also change `zappa_settings.json` and `Procfile` to point to `boot:app` instead?

**Comment by palewire** [comment]
I will.

**Comment by iandees** [comment]
FYI in the future you can make changes on an existing branch if you switch to the branch you created for this PR in the GitHub interface and hit edit on the file.

**Comment by palewire** [comment]
Oh duh. Sorry.

**Comment by iandees** [comment]
No prob. Just trying to share some knowledge.

**Pull request merged**
